language: csharp
solution: src/MySQLManager/MySQLManager.sln
before_script:
  - nuget restore src/MySQLManager/MySQLManager.sln
script:
- xbuild /p:Configuration=Release src/MySQLManager/MySQLManager.sln