language: csharp
solution: src/MySQLManager/MySQLManager.sln
before_script:
#  - nuget restore src/MySQLManager/MySQLManager.sln
  - msbuild /t:Restore
script:
  - msbuild /p:Configuration=Release src/MySQLManager/MySQLManager.sln